id: 026279eca3be44cd85803633d36d6951
initial_creation_type: ocr
source_metadata:
  volumes:
    6b8454ebf0274ad5a96dd931fec237ea:
      base_file: v019.txt
      image_group_id: I1PD95864
      title: རིམ་པ་ལྔ་པའི་དཀའ་འགྲེལ།
      total_pages: 1418
      volume_number: 19
