id: D716A7927
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:31:56+00:00'
last_modified: '2022-05-26T10:28:51.725079+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    63c4:
      image_group_id: I1PD95864
      title: རིམ་པ་ལྔ་པའི་དཀའ་འགྲེལ།
      total_pages: 1418
      order: 19
      base_file: 63c4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
